import 'package:flutter/material.dart';

List<int> categoryIcons = [
  Icons.folder.codePoint,
  Icons.home.codePoint,
  Icons.build.codePoint,
  Icons.bookmark.codePoint,
  Icons.description.codePoint,
  Icons.extension.codePoint,
  Icons.face.codePoint,
  Icons.favorite.codePoint,
  Icons.grade.codePoint,
  Icons.lightbulb_outline.codePoint,
  Icons.pets.codePoint,
  Icons.room.codePoint,
  Icons.shopping_cart.codePoint,
  Icons.work.codePoint,
  Icons.error.codePoint,
  Icons.movie.codePoint,
  Icons.radio.codePoint,
  Icons.call.codePoint,
  Icons.flag.codePoint,
  Icons.weekend.codePoint,
  Icons.audiotrack.codePoint,
  Icons.palette.codePoint,
  Icons.directions_bike.codePoint,
  Icons.directions_car.codePoint,
  Icons.directions_run.codePoint,
  Icons.flight.codePoint,
  Icons.restaurant_menu.codePoint,
  Icons.beach_access.codePoint,
  Icons.child_friendly.codePoint,
];
