import 'package:flutter/material.dart';

List<IconData> categoryIcons = [
  Icons.folder,
  Icons.home,
  Icons.build,
  Icons.bookmark,
  Icons.description,
  Icons.extension,
  Icons.face,
  Icons.favorite,
  Icons.grade,
  Icons.lightbulb_outline,
  Icons.pets,
  Icons.room,
  Icons.shopping_cart,
  Icons.work,
  Icons.error,
  Icons.movie,
  Icons.radio,
  Icons.call,
  Icons.flag,
  Icons.weekend,
  Icons.audiotrack,
  Icons.palette,
  Icons.directions_bike,
  Icons.directions_car,
  Icons.directions_run,
  Icons.flight,
  Icons.restaurant_menu,
  Icons.beach_access,
  Icons.child_friendly,
];
