import 'package:ant_icons/ant_icons.dart';

List<int> categoryIcons = [
  AntIcons.folderFilled.codePoint,
  AntIcons.homeFilled.codePoint,
  AntIcons.shoppingFilled.codePoint,
  AntIcons.carFilled.codePoint,
  AntIcons.giftFilled.codePoint,
  AntIcons.mailFilled.codePoint,
  AntIcons.phoneFilled.codePoint,
  AntIcons.messageFilled.codePoint,
  AntIcons.printerFilled.codePoint,
  AntIcons.codeFilled.codePoint,
  AntIcons.databaseFilled.codePoint,
  AntIcons.cloudFilled.codePoint,
  AntIcons.githubFilled.codePoint,
  AntIcons.gitlabFilled.codePoint,
  AntIcons.experimentFilled.codePoint,
  AntIcons.starFilled.codePoint,
  AntIcons.heartFilled.codePoint,
  AntIcons.smileFilled.codePoint,
  AntIcons.bulbFilled.codePoint,
  AntIcons.cameraFilled.codePoint,
  AntIcons.customerServiceFilled.codePoint,
  AntIcons.readFilled.codePoint,
  AntIcons.pictureFilled.codePoint,
  AntIcons.safetyCertificateFilled.codePoint,
  AntIcons.tagFilled.codePoint,
  AntIcons.trophyFilled.codePoint,
  AntIcons.toolFilled.codePoint,
  AntIcons.pushpinFilled.codePoint,
  AntIcons.profileFilled.codePoint,
  AntIcons.projectFilled.codePoint,
  AntIcons.fireFilled.codePoint,
];
