import 'package:ant_icons/ant_icons.dart';

List<int> categoryIcons = [
  AntIcons.folder.codePoint,
  AntIcons.home.codePoint,
  AntIcons.shopping.codePoint,
  AntIcons.car.codePoint,
  AntIcons.gift.codePoint,
  AntIcons.mail.codePoint,
  AntIcons.phone.codePoint,
  AntIcons.message.codePoint,
  AntIcons.printer.codePoint,
  AntIcons.code.codePoint,
  AntIcons.database.codePoint,
  AntIcons.cloud.codePoint,
  AntIcons.github.codePoint,
  AntIcons.gitlab.codePoint,
  AntIcons.experiment.codePoint,
  AntIcons.star.codePoint,
  AntIcons.heart.codePoint,
  AntIcons.smile.codePoint,
  AntIcons.bulb.codePoint,
  AntIcons.camera.codePoint,
  AntIcons.customerService.codePoint,
  AntIcons.read.codePoint,
  AntIcons.picture.codePoint,
  AntIcons.safety.codePoint,
  AntIcons.tag.codePoint,
  AntIcons.trophy.codePoint,
  AntIcons.tool.codePoint,
  AntIcons.pushpin.codePoint,
  AntIcons.profile.codePoint,
  AntIcons.project.codePoint,
  AntIcons.fire.codePoint,
];
